cones_matching_dist_theshold: 0.5
cone_position_extension_length: 0.05
distance_treshold_max: 7.0
distance_treshold_min: 0.7
level_threshold: -0.5
angle_threshold: 90.0
min_cluster_size: 3
max_cluster_size: 50
voxel_filter_leaf_size_x: 0.04
voxel_filter_leaf_size_y: 0.04
voxel_filter_leaf_size_z: 0.04